### ISSUE TITLE
Could example how to use?

### ISSUE THREAD

**Issue by thearabbit** [YerkoPalma/vue-print#4]

**Comment by YerkoPalma** [comment]
Hi @thearabbit :wave: 

This project is abandoned. I'm actually not using Vue, and this started before v2.x arrived, so it's uncompleted and legacy.

If you are still interested, I had a litle more of success in [this fiddle](https://jsfiddle.net/yerkopalma/3utxqzto/7/) I guess you can work from there, start your own module or continue from this one what ever you want :)

**Comment by thearabbit** [comment]
Thanks, It work fine.
